name: Trigger Netlify Build

on:
  push:
    branches:
      - publish

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST to Netlify Build Hook
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK_URL }}